#!/usr/bin/env python3
"""Generate client/icons.js from client/icons/*.svg (Solar Icon Set Linear).

Single source of truth: client/icons/*.svg files.
Output: window.TAPFLOW_ICONS = {groups:[{id,label,icons:[names]}], svg:{name:svgString}}

Run: python3 tools/gen_icons_js.py   (from repo root)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ICONS_DIR = ROOT / "client" / "icons"
OUT = ROOT / "client" / "icons.js"

GROUPS = [
    ("settings", "设置", [
        "settings", "settings-min", "tuning", "tuning-2", "widget",
    ]),
    ("devices", "设备", [
        "display", "monitor", "cpu", "keyboard", "laptop", "smartphone",
        "tablet", "mouse", "power", "bolt", "battery-full", "battery-low",
        "keycap",
    ]),
    ("audio", "音频", [
        "volume", "volume-loud", "volume-mute", "mic", "mic-2", "headphones",
        "speaker", "play", "pause", "stop", "music-note", "soundwave",
        "bell", "bell-off", "bell-bing", "bell-remove",
    ]),
    ("actions", "操作", [
        "arrow-up", "arrow-down", "arrow-left", "arrow-right", "enter",
        "refresh", "restart", "search", "copy", "clipboard", "trash",
        "check-circle", "close-circle", "plus-circle", "fullscreen",
        "menu-dots", "folder", "folder-open", "home",
    ]),
    ("network", "网络", [
        "wifi-router", "bluetooth", "usb", "command", "code", "bug",
        "cloud-storage", "lock", "lock-open", "lock-keyhole", "key",
        "eye", "shield",
    ]),
    ("editing", "编辑", [
        "backspace", "eraser", "text-bold", "text-cross", "link",
        "link-broken", "text-field", "paragraph", "pipette", "filters",
        "layers", "ruler", "crop", "paint-roller",
    ]),
    ("media", "媒体", [
        "camera", "gallery", "video-frame", "record", "videocamera",
        "clapperboard", "cloud", "cloud-sun", "cloud-rain", "cloud-bolt",
        "snowflake", "fog", "clouds",
    ]),
    ("messages", "消息", [
        "chat-dots", "chat-line", "chat-round", "chat-video", "chat-check",
        "letter", "user", "user-check", "user-block",
    ]),
    ("navigation", "导航", [
        "map-point", "gps", "compass", "global", "map-arrow", "branching",
    ]),
    ("time", "时间", [
        "calendar", "calendar-date", "stopwatch", "timer", "history",
        "clock", "alarm",
    ]),
    ("misc", "其他", [
        "sun", "moon", "chart", "pie-chart", "graph-up", "graph-down",
        "course-up", "diagram", "palette", "gamepad",
    ]),
]


def compact(svg: str) -> str:
    svg = re.sub(r"^\s*<\?xml[^>]*>\s*", "", svg)
    svg = re.sub(r">\s+<", "><", svg.strip())
    svg = re.sub(r"\s+", " ", svg)
    return svg


def main() -> int:
    picked = {p.stem for p in ICONS_DIR.glob("*.svg")}
    grouped = {name for _, _, names in GROUPS for name in names}
    missing_files = sorted(grouped - picked)
    ungrouped = sorted(picked - grouped)
    if missing_files or ungrouped:
        if missing_files:
            print("MISSING SVG FILES:", missing_files, file=sys.stderr)
        if ungrouped:
            print("UNGROUPED SVG FILES:", ungrouped, file=sys.stderr)
        return 1

    svgs = {}
    for name in sorted(grouped):
        raw = (ICONS_DIR / f"{name}.svg").read_text()
        svgs[name] = compact(raw)

    groups_js = json.dumps(
        [{"id": gid, "label": label, "icons": names} for gid, label, names in GROUPS],
        ensure_ascii=False, separators=(",", ":"),
    )
    svg_js = json.dumps(svgs, ensure_ascii=False, separators=(",", ":"))

    OUT.write_text(
        "/* AUTO-GENERATED by tools/gen_icons_js.py — do not edit by hand. "
        "Source: client/icons/*.svg (Solar Icon Set Linear, free for commercial use). */\n"
        "window.TAPFLOW_ICONS={groups:" + groups_js + ",svg:" + svg_js + "};\n"
    )
    print(f"OK: {len(svgs)} icons -> {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
